MOB-3861 Clean the outdated analytics events in the UI SDK
karhoo/karhoo-android-ui-sdk pull request #287
Opened 2022-02-02 21:30 UTC by mionescu95

## JIRA
[MOB-3861](https://karhoo.atlassian.net/browse/MOB-3861)

## DESCRIPTION
Marked as deprecated all the unused or not so used analytics.

## Types of changes

What types of changes does your code introduce to the project?
_Put an `x` in the boxes that apply_

- [ ] Bugfix 
- [ ] New feature 
- [x] Tech Debt
- [ ] Breaking change 
- [ ] Documentation Update
- [ ] Other: *define what type of change it is*

## CHECKLIST

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. This is simply a reminder of what we are going to look for before merging code._
Please review the guidelines for contributing to this repository.

- [ ] All work relating to the ticket is complete (Code complete/Acceptance Criteria met)
- [ ] Lint and unit tests pass locally (if appropriate)
- [ ] Added tests that prove the fix is effective or that feature works (if appropriate)
- [ ] Documentation (if appropriate)

## SCREENSHOTS
[Add screenshots if any for changes you have made to the App/UI]

2022-02-02 22:01 UTC, mohadian requested changes

2022-02-02 22:01 UTC, mohadian commented on uisdk/src/main/java/com/karhoo/uisdk/analytics/Analytics.kt
> +    @Deprecated("ToBeDeleted")
You can remove the deprecated method. We don't need to keep them. 
We will communicate with effected partners

2022-02-03 08:33 UTC, mateid-kr approved these changes

2022-02-03 12:41 UTC, mohadian approved these changes

2022-02-03 13:14 UTC, merged