[MOB-3833] No coverage screen
karhoo/karhoo-android-ui-sdk pull request #341
Opened 2022-03-30 13:10 UTC by EdwardW2

## JIRA
[MOB-3833](https://karhoo.atlassian.net/browse/MOB-3833)

## DESCRIPTION
[Create a description of what you have changed in this branch]

## Types of changes

What types of changes does your code introduce to the project?
_Put an `x` in the boxes that apply_

- [ ] Bugfix 
- [ ] New feature 
- [ ] Tech Debt
- [ ] Breaking change 
- [ ] Documentation Update
- [ ] Other: *define what type of change it is*

## CHECKLIST

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. This is simply a reminder of what we are going to look for before merging code._
Please review the guidelines for contributing to this repository.

- [ ] All work relating to the ticket is complete (Code complete/Acceptance Criteria met)
- [ ] Lint and unit tests pass locally (if appropriate)
- [ ] Added tests that prove the fix is effective or that feature works (if appropriate)
- [ ] Documentation (if appropriate)

## SCREENSHOTS
[Add screenshots if any for changes you have made to the App/UI]

2022-04-12 07:45 UTC, mateid-kr commented on uisdk/src/main/java/com/karhoo/uisdk/screen/booking/quotes/errorview/QuotesErrorView.kt
> +            reason.subtitle,
Good catch!

2022-04-12 07:45 UTC, mateid-kr commented on uisdk/src/main/java/com/karhoo/uisdk/screen/booking/quotes/errorview/QuotesErrorView.kt
> +            reason.subtitle,
Good catch!

2022-04-12 07:47 UTC, mateid-kr approved these changes

2022-04-12 07:47 UTC, mateid-kr commented on uisdk/src/main/java/com/karhoo/uisdk/screen/booking/quotes/list/QuotesRecyclerView.kt
> +                        "Contact us",
This should be localized

2022-04-12 07:47 UTC, mateid-kr requested changes

2022-04-27 09:12 UTC, dianakarh reviewed
CircleCI failing because of missing translations:
Errors found:
  
  /home/circleci/project/uisdk/src/main/res/values/strings.xml:274: Error: "kh_uisdk_no_availability_subtitle" is not translated in "de" (German), "en" (English), "it" (Italian), "fr" (French), "es" (Spanish), "nl" (Dutch) [MissingTranslation]
      <string name="kh_uisdk_no_availability_subtitle">Please select another time</string>
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  /home/circleci/project/uisdk/src/main/res/values/strings.xml:275: Error: "kh_uisdk_no_availability_title" is not translated in "de" (German), "en" (English), "it" (Italian), "fr" (French), "es" (Spanish), "nl" (Dutch) [MissingTranslation]
      <string name="kh_uisdk_no_availability_title">No availability for the requested time</string>

2022-05-02 08:31 UTC, mateid-kr approved these changes

2022-05-04 08:15 UTC, merged