MOB-4200   [Quote] Remove "All" in filters screen and modify selectio…
karhoo/karhoo-android-ui-sdk pull request #409
Opened 2022-08-02 07:45 UTC by mionescu95

## JIRA
[MOB-4200](https://karhoo.atlassian.net/browse/MOB-4200)

## DESCRIPTION
[Create a description of what you have changed in this branch]

## Types of changes

What types of changes does your code introduce to the project?
_Put an `x` in the boxes that apply_

- [ ] Bugfix 
- [x] New feature 
- [ ] Tech Debt
- [ ] Breaking change 
- [ ] Documentation Update
- [ ] Other: *define what type of change it is*

## CHECKLIST

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. This is simply a reminder of what we are going to look for before merging code._
Please review the guidelines for contributing to this repository.

- [ ] All work relating to the ticket is complete (Code complete/Acceptance Criteria met)
- [ ] Lint and unit tests pass locally (if appropriate)
- [ ] Added tests that prove the fix is effective or that feature works (if appropriate)
- [ ] Documentation (if appropriate)

## SCREENSHOTS
[Add screenshots if any for changes you have made to the App/UI]

2022-08-02 09:47 UTC, mateid-kr commented on uisdk/src/main/java/com/karhoo/uisdk/screen/booking/quotes/filterview/ServiceAgreementsFilter.kt
> +                ) == true
Think we can put each one of these in a function () : Boolean to simplify the sintax

Something like 
quoteContainsTag(quote, selectedTypes, tag): Boolean { 
 return (quote.serviceAgreements?.freeWaitingTime != null && selectedTypes.any {
                        it.fixedTag?.contains(
                            tag
                        ) == true
                    })
}

And then replace the paragrahps from 12 to 35

2022-08-02 12:28 UTC, dianakarh commented on uisdk/src/main/java/com/karhoo/uisdk/screen/booking/quotes/filterview/QuoteTypesFilter.kt
> +                ((quote.quoteType.ordinal == 1 || quote.quoteType.ordinal == 2) && selectedTypes.any { it.fixedTag?.contains(ESTIMATED_TAG) == true || it.fixedTag?.contains(
I don't like the fact that we're comparing ordinals. 0, 1, and 2 are not obvious enough as to what they represent. Also, the enums used for filtering are an internal convention. We can choose to reorder them for consistency between platforms which will mess up this logic. Please compare with the label, not the ordinal wherever it is the case. e.g. of the expected outcome: `quote.quoteType == QuoteType.FIXED`

2022-08-02 12:29 UTC, dianakarh requested changes
enum handling improvement required

2022-08-03 14:09 UTC, dianakarh approved these changes

2022-08-03 14:32 UTC, merged