Retrieve proper key for Adyen payments
karhoo/karhoo-android-ui-sdk pull request #490
Opened 2022-11-28 09:03 UTC by mionescu95

## JIRA
[MOB-4473](https://karhoo.atlassian.net/browse/MOB-4473)

## DESCRIPTION
[Create a description of what you have changed in this branch]

## Types of changes

What types of changes does your code introduce to the project?
_Put an `x` in the boxes that apply_

- [ ] Bugfix 
- [ ] New feature 
- [ ] Tech Debt
- [ ] Breaking change 
- [ ] Documentation Update
- [ ] Other: *define what type of change it is*

## CHECKLIST

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. This is simply a reminder of what we are going to look for before merging code._
Please review the guidelines for contributing to this repository.

- [ ] All work relating to the ticket is complete (Code complete/Acceptance Criteria met)
- [ ] Lint and unit tests pass locally (if appropriate)
- [ ] Added tests that prove the fix is effective or that feature works (if appropriate)
- [ ] Documentation (if appropriate)

## SCREENSHOTS
[Add screenshots if any for changes you have made to the App/UI]

2022-11-29 12:36 UTC, dianakarh commented on uisdk/src/adyen/java/com/karhoo/uisdk/AdyenPaymentPresenter.kt
> +        val key: String = if(userStore.paymentProvider?.provider?.version.equals("v68", ignoreCase = true))
The version should be >= 68. Let's not get stuck on v68 only

2022-11-29 12:37 UTC, dianakarh commented on uisdk/src/adyen/java/com/karhoo/uisdk/AdyenPaymentPresenter.kt
> +        if(!userStore.paymentProvider?.provider?.version.equals("v68", ignoreCase = true)) {
The rule is >= v69 => clientKey, else => public key

2022-11-29 12:40 UTC, dianakarh requested changes
The key selection logic needs updating.
if adyen v >= 68 => clientKey
else => publicKey

2022-11-29 15:59 UTC, dianakarh approved these changes
Unblocking the PR before going OOO. @mateid-kr please review this when done.

2022-12-01 11:50 UTC, mateid-kr approved these changes

2022-12-01 11:54 UTC, merged